
name: infosys
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pillow
  - scipy
  - transformers
  - opencv
  - matplotlib
  - numpy
  - tensorflow
  - tensorflow-hub
  - pytorch
  - torchvision
  - pip:
      - torch
