name: infosys
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pillow
  - scipy
  - transformers
  - opencv
  - matplotlib
  - numpy
  - tensorflow
  - tensorflow-hub
  - jupyter
  - ipywidgets
  - pip:
      - torch==2.0.1
      - torchvision==0.15.2